# Generated by Django 4.0.3 on 2022-04-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('contact_prof', models.CharField(max_length=15)),
                ('date_d_adhesion', models.DateField(default='')),
                ('chef_departement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Prof',
                'verbose_name_plural': 'Profs',
            },
            bases=('users.user',),
        ),
    ]
